### ISSUE TITLE
Create the layout CSS

### ISSUE THREAD

**Issue by nfroidure** [ChtiJS/chtijs.francejs.org#78]
To do so, check the old styles here : https://github.com/ChtiJS/chtijs.francejs.org/tree/master/documents/less

Since we don't use less anymore, please use CSS variables ( see here https://github.com/nfroidure/politics/blob/main/styles/main.css#L6-L66 for an example )

## Todo
- [ ] create CSS vars
- [ ] build the main layout
- [ ] add some instructions on the design in the readme file
- [ ] compare to the result in the site https://chtijs.francejs.org/
