### ISSUE TITLE
Create the meetup list

### ISSUE THREAD

**Issue by nfroidure** [ChtiJS/chtijs.francejs.org#80]
To do so, list the markdown files and pickup the metadata. Convert the current metadata to frontmatter ones ( see here https://raw.githubusercontent.com/nfroidure/politics/main/contents/blog/2020-02-26-education-numerique.md ) and read those metadata to display the meetup list (see a full example here: https://github.com/nfroidure/politics/blob/main/src/pages/blog/index.tsx#L186-L236 ).

## Todo
- [ ] reorganise the markdown files to be more simple
- [ ] code the page
- [ ] add a readme section to explain how to create a meetup entry
